# Use with: accelerate launch --config_file acc_config.yaml ...
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
num_processes: 2
num_machines: 1
gpu_ids: "0,5"
machine_rank: 0
main_process_ip: null
main_process_port: 29500
mixed_precision: bf16         # change to "fp16" if your GPUs don't support bf16
downcast_bf16: "no"
use_cpu: false
tpu_name: null
tpu_zone: null
dynamo_backend: "no"
rdzv_backend: static
